### ISSUE TITLE
Support foreign references in parameters directly

### ISSUE THREAD

**Issue by raveclassic** [devexperts/swagger-codegen-ts#90]
```yaml
parameters:
  - name: times
    in: query
    schema:
      $ref: './shared.yaml#/components/times'
```

Current implementation assumes that there will be a separate run of generation for referenced entities in foreign spec. However such generation is only run for local references in local `components` section.
